---
readarr_enabled: false
readarr_available_externally: "false"
readarr_proxy: false

# directories
readarr_data_directory: "{{ docker_home }}/readarr"
readarr_books_directory: "{{ books_root }}"
readarr_audio_books_directory: "{{ audiobooks_root }}"
readarr_download_directory: "{{ downloads_root }}"

# uid/gid
readarr_user_id: "0"
readarr_group_id: "0"

# network
readarr_hostname: "readarr"
