---
bazarr_enabled: false
bazarr_available_externally: "false"
bazarr_proxy: false

# directories
bazarr_data_directory: "{{ docker_home }}/bazarr/config"
bazarr_tv_directory: "{{ tv_root }}"
bazarr_movies_directory: "{{ movies_root }}"

# uid/gid
bazarr_user_id: "0"
bazarr_group_id: "0"

# network
bazarr_port: "6767"
bazarr_hostname: "bazarr"
