---
- name: Create overseerr Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ overseerr_data_directory }}"
    - "{{ overseerr_data_directory }}/config"
- name: overseerr Docker Container
  docker_container:
    name: overseerr
    image: sctx/overseerr
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes:
      - "{{ overseerr_data_directory }}/config:/app/config"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    env:
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.enable: "{{ overseerr_available_externally }}"
      traefik.http.routers.overseerr.entrypoints: "websecure,web"
      traefik.http.routers.overseerr.rule: "Host(`{{ overseerr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.overseerr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.overseerr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.overseerr.loadbalancer.server.port: "5055"
      traefik.http.routers.overseerr.middlewares: "{{ port|default(omit) if nas_auth_middleware is not defined else nas_auth_middleware }}"
