---
lidarr_enabled: false
lidarr_available_externally: "false"

# directories
lidarr_music_directory: "{{ music_root }}"
lidarr_downloads_directory: "{{ downloads_root }}"
lidarr_data_directory: "{{ docker_home }}/lidarr"

# uid/gid
lidarr_user_id: "0"
lidarr_group_id: "0"

# network
lidarr_port: "8686"
lidarr_hostname: "lidarr"
