
---
- name: Create pialert Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pialert_config_directory }}"
    - "{{ pialert_config_directory }}/logs"
    - "{{ pialert_config_directory }}/config"

- name: pialert Docker Container
  docker_container:
    name: pialert
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    #image: jokobsk/pi.alert:latest
    image: tmp
    pull: false
    volumes:
      - "{{ pialert_config_directory }}/config:/home/pi/pialert/config:rw"
      - "{{ pialert_config_directory }}/logs:/home/pi/pialert/front/log:rw"
      - "{{ pihole_data_directory }}/pihole:/etc/pihole:ro"
    ports:
      - "{{ pialert_port }}:20211"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      # HOST_USER_ID: "1000"
      # HOST_USER_GID: "1000" 
      # USER_ID: "{{ pialert_user_id }}"
      # USER_GID: "{{ pialert_user_id }}"
      PORT: "{{ pialert_port }}"
      PIHOLE_ACTIVE: "true"
      DHCP_ACTIVE: "true"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    labels:
      autoheal: "true"
      traefik.enable: "{{ pialert_available_externally }}"
      traefik.http.routers.pialert.entrypoints: "websecure"
      traefik.http.routers.pialert.rule: "Host(`{{ pialert_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.pialert.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.pialert.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.pialert.loadbalancer.server.port: "20211"
#The default password is 123456. To change the password run /home/pi/pialert/back/pialert-cli in the container
