---
- name: watchlistarr Docker Container
  docker_container:
    name: watchlistarr
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: nylonee/watchlistarr
    pull: true
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ docker_home }}/traefik/certs_dump/certs:/ssl"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    env:
      SONARR_API_KEY: "{{ watchistarr_sonarr_key }}"
      RADARR_API_KEY: "{{ watchistarr_radarr_key }}"
      PLEX_TOKEN: "{{ watchistarr_plex_key }}"
      SONARR_BASE_URL: "https://sonarr.{{ ansible_nas_domain }}"
      RADARR_BASE_URL: "https://radarr.{{ ansible_nas_domain }}"
      REFRESH_INTERVAL_SECONDS: "5"
      ALLOW_MOVIE_DELETING: "false"
      ALLOW_ENDED_SHOW_DELETING: "false"
    labels:
      autoheal: "true"
