- name: build zfswatcher image
  docker_image:
    name: myzfswatcher
    build:
      path: "{{ role_path }}/files/"
      cache_from:
        - myzfswatcher:latest
    source: build
    state: present
    force_source: true
- name: zfswatcher
  docker_container:
    name: zfswatcher
    image: myzfswatcher
    networks:
      - name: "{{ nas_bridge_network }}"
    volumes:
      - "{{ zfswatcher_data_directory }}/config:/zfswatcher_config:rw"
      - "{{ zfswatcher_data_directory }}/logs:/var/log/zfswatcher:rw"
      - "/dev/log:/dev/log:rw"
      - "/etc/hostid:/etc/hostid:ro"
    devices:
      - "/dev/zfs:/dev/zfs:rw"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 32m
    labels:
      traefik.enable: "{{ zfswatcher_available_externally }}"
      traefik.http.routers.zfswatcher.rule: "Host(`{{ zfswatcher_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.zfswatcher.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.zfswatcher.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.zfswatcher.loadbalancer.server.port: "{{ zfswatcher_port|string }}"
      com.centurylinklabs.watchtower.enable: "false"
