---
language: python

services: docker

env:
  - playbook: nas.yml
    distro: ubuntu1804
    test_syntax: true
    test_playbook: false
    test_idempotence: false

install:
  - pip install ansible-lint

script:
  - cp ${PWD}/tests/test.yml ${PWD}/group_vars/all.yml
  - ansible-lint ${PWD}/nas.yml
  - ${PWD}/tests/test.sh