---
- hosts: all

  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  roles:
    ###
    ### Requirements
    ###
    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint
      when: (samba_enabled | default(False))

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint
      when: (nfs_enabled | default(False))

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    ###
    ### Ansible-NAS Roles
    ###
    - role: s3backup
      tags:
        - s3backup
        - always
      when: (s3backup_enabled | default(False))

    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas

    ###
    ### needs to be towards the top
    ###
    - role: expressvpn
      tags: [ never, expressvpn ]
      when: (expressvpn_enabled | default(False))

    - role: wgeasy
      tags: wgeasy
      when: (wgeasy_enabled | default(False))

    - role: networks
      tags: [ always ]

    ###
    ### Applications
    ###
    - role: authentik
      tags:
        - authentik
      when: (authentik_enabled | default(False))

    - role: authelia
      tags:
        - authelia
      when: (authelia_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: pihole
      tags:
        - always
        - pihole
        - pihole_dns
      when: (pihole_enabled | default(False))

    - role: openvpn
      tags:
        - openvpn
      when: (openvpn_enabled | default(False))

    ##
    ## put this near top or else we get alerts saying they aren't availble to sanorr,radarr...
    ##
    - role: sabnzbd
      tags:
        - sabnzbd
      when: (sabnzbd_enabled | default(False))

    - role: pialert
      tags:
        - pialert
      when: (pialert_enabled | default(False))

    - role: transmission
      tags:
        - transmission
      when: (transmission_enabled | default(False))

    - role: airsonic
      tags:
        - airsonic
      when: (airsonic_enabled | default(False))

    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(False))

    - role: bitwarden
      tags:
        - bitwarden
      when: (bitwarden_enabled | default(False))

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
      when: (cloudflare_ddns_enabled | default(False))

    - role: couchpotato
      tags:
        - couchpotato
      when: (couchpotato_enabled | default(False))

    - role: duplicati
      tags:
        - duplicati
      when: (duplicati_enabled | default(False))

    - role: emby
      tags:
        - emby
      when: (emby_enabled | default(False))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(False))

    - role: varken
      tags:
        - varken
      when: (varken_enabled | default(False))

    - role: muximux
      tags:
        - muximux
      when: (muximux_enabled | default(False))

    - role: umi
      tags:
        - umi
      when: (umi_enabled | default(False))

    - role: transmission-with-openvpn
      tags:
        - transmission_with_openvpn_enabled
      when: (transmission_with_openvpn_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: komga
      tags:
        - komga
      when: (komga_enabled | default(False))

    - role: hakuneko
      tags:
        - hakuneko
      when: (hakuneko_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: organizr
      tags:
        - organizr
      when: (organizr_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: ombi
      tags:
        - ombi
      when: (ombi_enabled | default(False))

    - role: owncloud
      tags:
        - owncloud
      when: (owncloud_enabled | default(False))

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: readarr
      tags:
        - readarr
      when: (readarr_enabled | default(False))

    - role: speakarr
      tags:
        - speakarr
      when: (speakarr_enabled | default(False))

    - role: scrutiny
      tags:
        - scrutiny
      when: (scrutiny_enabled | default(False))

    - role: pushover
      tags:
        - pushover
      when: (pushover_enabled | default(False))

    - role: minecraft
      tags:
        - minecraft
      when: (minecraft_enabled | default(False))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: mealie
      tags:
        - mealie
      when: (mealie_enabled | default(False))

    - role: kometa
      tags:
        - kometa
      when: (kometa_enabled | default(False))

    - role: tandoor
      tags:
        - tandoor
      when: (tandoor_enabled | default(False))

    - role: kitchenowl
      tags:
        - kitchenowl
      when: (kitchenowl_enabled | default(False))

    - role: grimoire
      tags:
        - grimoire
      when: (grimoire_enabled | default(False))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(False))

    - role: syncthing
      tags:
        - syncthing
      when: (syncthing_enabled | default(False))

    - role: utorrent
      tags:
        - utorrent
      when: (utorrent_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: subsonic
      tags:
        - subsonic
      when: (subsonic_enabled | default(False))

    - role: navidrome
      tags:
        - navidrome
      when: (navidrome_enabled | default(False))

    - role: funkwhale
      tags:
        - funkwhale
      when: (funkwhale_enabled | default(False))

    - role: librephotos
      tags:
        - librephotos
      when: (librephotos_enabled | default(False))

    - role: immich
      tags:
        - immich
      when: (immich_enabled | default(False))

    - role: librenms
      tags:
        - librenms
      when: (librenms_enabled | default(False))

    - role: audiobookshelf
      tags:
        - audiobookshelf
      when: (audiobookshelf_enabled | default(False))

    - role: speedtesttracker
      tags:
        - speedtesttracker
      when: (speedtesttracker_enabled | default(False))

    - role: plextraktsync
      tags:
        - plextraktsync
      when: (plextraktsync_enabled | default(False))

    - role: dozzle
      tags:
        - dozzle
      when: (dozzle_enabled | default(False))

    - role: trilium
      tags:
        - trilium
      when: (trilium_enabled | default(False))

    - role: watchlistarr
      tags:
        - watchlistarr
      when: (watchlistarr_enabled | default(False))

    - role: overseerr
      tags:
        - overseerr
      when: (overseerr_enabled | default(False))

    - role: uptimekuma
      tags:
        - uptimekuma
      when: (uptimekuma_enabled | default(False))

    - role: monitorr
      tags:
        - monitorr
      when: (monitorr_enabled | default(False))

    - role: prometheus
      tags:
        - prometheus
      when: (prometheus_enabled | default(False))
     
    - role: webhookd
      tags:
        - webhookd
      when: (webhookd_enabled | default(False))

    - role: papermerge
      tags:
        - papermerge
      when: (papermerge_enabled | default(False))

    - role: zfswatcher
      tags:
        - zfswatcher
      when: (zfswatcher_enabled | default(False))

    - role: wyze-bridge
      tags:
        - wyze-bridge
      when: (wyze_enabled | default(False))

  tasks:
  - import_tasks: tasks/firefly.yml
    when: (firefly_enabled | default(False))
    tags: firefly

  - import_tasks: tasks/tautulli.yml
    when: (tautulli_enabled | default(False))
    tags: tautulli

  - import_tasks: tasks/pyload.yml
    when: (pyload_enabled | default(False))
    tags: pyload

  - import_tasks: tasks/thelounge.yml
    when: (thelounge_enabled | default(False))
    tags: thelounge

  - import_tasks: tasks/mylar.yml
    when: (mylar_enabled | default(False))
    tags: mylar

  - import_tasks: tasks/ubooquity.yml
    when: (ubooquity_enabled | default(False))
    tags: ubooquity

  - import_tasks: tasks/glances.yml
    when: (glances_enabled | default(False))
    tags: glances

  - import_tasks: tasks/znc.yml
    when: (znc_enabled | default(False))
    tags: znc

  - import_tasks: tasks/miniflux.yml
    when: (miniflux_enabled | default(False))
    tags: miniflux

  - import_tasks: tasks/gitlab.yml
    when: (gitlab_enabled | default(False))
    tags: gitlab

  - import_tasks: tasks/timemachine.yml
    when: (timemachine_enabled | default(False))
    tags: timemachine

  - import_tasks: tasks/stats.yml
    when: (stats_enabled | default(False))
    tags: stats

  - import_tasks: tasks/static.yml
    when: (static_enabled | default(False))
    tags: static

  - import_tasks: tasks/google-ddns.yml
    when: (gddns_enabled | default(False))
    tags: google-ddns

  - import_tasks: tasks/guacamole.yml
    when: (guacamole_enabled | default(False))
    tags: guacamole

  - import_tasks: tasks/minidlna.yml
    when: (minidlna_enabled | default(False))
    tags: minidlna

  - import_tasks: tasks/get_iplayer.yml
    when: (get_iplayer_enabled | default(False))
    tags: get_iplayer

  - import_tasks: tasks/mymediaforalexa.yml
    when: (mymediaforalexa_enabled | default(False))
    tags: mymediaforalexa

  - import_tasks: tasks/jackett.yml
    when: (jackett_enabled | default(False))
    tags: jackett

  - import_tasks: tasks/joomla.yml
    when: (joomla_enabled | default(False))
    tags: joomla

  - import_tasks: tasks/nzbget.yml
    when: (nzbget_enabled | default(False))
    tags: nzbget

  - import_tasks: tasks/wallabag.yml
    when: (wallabag_enabled | default(False))
    tags: wallabag

  - import_tasks: tasks/mosquitto.yml
    when: (mosquitto_enabled | default(False))
    tags: mosquitto

  - import_tasks: tasks/homebridge.yml
    when: (homebridge_enabled | default(False))
    tags: homebridge

  - import_tasks: tasks/calibre.yml
    when: (calibre_enabled | default(False))
    tags: calibre

  - import_tasks: tasks/openhab.yml
    when: (openhab_enabled | default(False))
    tags: openhab

  - import_tasks: tasks/jellyfin.yml
    when: (jellyfin_enabled | default(False))
    tags: jellyfin

  - import_tasks: tasks/cloudcmd.yml
    when: (cloudcmd_enabled | default(False))
    tags: cloudcmd

  - import_tasks: tasks/krusader.yml
    when: (krusader_enabled | default(False))
    tags: krusader

  - import_tasks: tasks/youtubedlmaterial.yml
    when: (youtubedlmaterial_enabled | default(False))
    tags: youtubedlmaterial

  - import_tasks: tasks/virtual_desktop.yml
    when: (virtual_desktop_enabled | default(False))
    tags: virtual_desktop

  - import_tasks: tasks/pytivo.yml
    when: (pytivo_enabled | default(False))
    tags: pytivo

  - import_tasks: tasks/autoheal.yml
    when: (autoheal_enabled | default(False))
    tags: autoheal

  handlers:
  - name: 'restart prometheus'
    docker_container:
      name: prometheus
      restart: yes
  - name: 'restart blackbox'
    docker_container:
      name: blackbox
      restart: yes
