---
- name: Watchtower Docker Container
  docker_container:
    name: watchtower
    log_options:
      max-size: 256m
      max-file: 1
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    command: "{{ watchtower_command }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 32m
