- name: autoheal
  docker_container:
    name: autoheal
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: willfarrell/autoheal
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      AUTOHEAL_CONTAINER_LABEL: all
    restart_policy: unless-stopped
    memory: 64m
    networks:
      - name: "{{ nas_bridge_network }}"
