---
- name: Set login banner
  template:
    src: ansible-nas/motd.txt
    dest: /etc/motd

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages
  apt:
    upgrade: true
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - smartmontools
    - htop
    - zfsutils-linux
    - bonnie++
    - unzip
    - lm-sensors
  register: result
  until: result is succeeded

#  - name: Configure smartmontools

- name: "Set hostname to {{ ansible_nas_hostname }}"
  hostname:
    name: "{{ ansible_nas_hostname }}"

- name: "Set timezone to {{ ansible_nas_timezone }}"
  timezone:
    name: "{{ ansible_nas_timezone }}"

- name: "Permission share directories"
  file:
    path: "{{ item.path }}"
    owner: ansible-nas
    group: ansible-nas
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"