- name: Glances Docker Container
  docker_container:
    name: glances
    log_options:
      max-size: 256m
      max-file: "1"
    image: nicolargo/glances:dev
    pull: true
    ports:
      - "{{ glances_port_one }}:61208"
      - "{{ glances_port_two }}:61209"
    volumes:
      #- "/glances.conf:/glances/conf/glances.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ glances_data_directory }}:/glances/conf"
    pid_mode: host
    env:
      GLANCES_OPT: "-w"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 128m
    privileged: true
    labels:
      traefik.enable: "{{ glances_available_externally }}"
      traefik.http.routers.glances.entrypoints: "web,websecure"
      traefik.http.routers.glances.rule: "Host(`glances.{{ ansible_nas_domain }}`)"
      traefik.http.routers.glances.tls.certresolver: "letsencrypt"
      traefik.http.routers.glances.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.glances.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.glances.loadbalancer.server.port: "61208"
