---
- name: Create google-ddns container
  docker_container:
    name: google-ddns
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: dragoncube/google-domains-ddns
    pull: true
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 32m
    volumes:
      - "{{ gddns_data_directory }}:/config"
      - "/etc/localtime:/etc/localtime"
    networks:
      - name: "{{ nas_bridge_network }}"
