---
- name: Create Joomla Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/joomla"

- name: Create MySQL Directorys for Joomla
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/JoomlaDB"

- name: MySQL Docker Container for Joomla
  docker_container:
    name: mysql_joomla
    image: mysql
    pull: true
    volumes:
      - "{{ docker_home }}/JoomlaDB:/var/lib/mysql"
    env:
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    restart_policy: unless-stopped
    memory: 1g

- name: joomla Docker Container
  docker_container:
    name: joomla
    image: joomla
    pull: true
    volumes:
      - "{{ docker_home }}/joomla:/var/www/html:rw"
    ports:
      - "8181:80"
    links:
      - "mysql_joomla:mysql_joomla"
    env:
      JOOMLA_DB_PASSWORD: "{{ mysql_root_password }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "joomla"
      traefik.frontend.rule: "Host: joomla.{{ ansible_nas_domain }}"
      traefik.enable: "{{ joomla_available_externally }}"
      traefik.port: "80"
