- name: MiniDLNA Docker Container
  docker_container:
    name: minidlna
    log_options:
      max-size: 256m
      max-file: 1
    image: vladgh/minidlna
    pull: true
    volumes:
      - "{{ minidlna_media_directory1 }}:/media1:rw"
      - "{{ minidlna_media_directory2 }}:/media2:rw"
    env:
      MINIDLNA_MEDIA_DIR1: "/media1"
      MINIDLNA_MEDIA_DIR2: "/media2"
      MINIDLNA_FRIENDLY_NAME: "{{ minidlna_friendly_name }}"
      MINIDLNA_PORT: "8201"
    network_mode: host
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g
