- name: Create mymedia for alexa Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mymediaforalexa_media_directory }}"
    - "{{ mymediaforalexa_data_directory }}"

- name: mymedia for alexa Docker Container
  docker_container:
    name: mymediaforalexa
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: bizmodeller/mymediaforalexa
    pull: true
    volumes:
      - "{{ mymediaforalexa_media_directory }}:/medialibrary:rw"
      - "{{ mymediaforalexa_data_directory }}:/datadir:rw"
    network_mode: host
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g

