---
- name: Create pyLoad Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ pyload_config_directory }}"
    - "{{ pyload_download_directory }}"

- name: pyLoad Docker Container
  docker_container:
    name: pyload
    log_options:
      max-size: 256m
      max-file: "1"
    image: writl/pyload
    pull: true
    volumes:
      - "{{ pyload_config_directory }}:/opt/pyload/pyload-config:rw"
      - "{{ pyload_download_directory }}:/opt/pyload/Downloads:rw"
    networks:
      - name: "{{ nas_bridge_network }}"
 #   ports:
 #     - "{{ pyload_port }}:8000"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      UID: "{{ pyload_user_id }}"
      GID: "{{ pyload_group_id }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g
    labels:
      traefik.enable: "{{ pyload_available_externally }}"
      traefik.http.routers.pyload.entrypoints: "web,websecure"
      traefik.http.routers.pyload.rule: "Host(`pyload.{{ ansible_nas_domain }}`)"
      traefik.http.routers.pyload.tls.certresolver: "letsencrypt"
      traefik.http.routers.pyload.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.pyload.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.pyload.loadbalancer.server.port: "8000"
