---
- name: Create InfluxDB and Telegraf Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb_data_directory }}"
    - "{{ telegraf_data_directory }}"

- name: Create Grafana Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "472"
    recurse: yes
  with_items:
    - "{{ grafana_data_directory }}"
    - "{{ grafana_data_directory }}/data"
    - "{{ grafana_data_directory }}/data/dashboards/ansible-nas"
    - "{{ grafana_data_directory }}/config/"
    - "{{ grafana_data_directory }}/config/provisioning"
    - "{{ grafana_data_directory }}/config/provisioning/datasources"
    - "{{ grafana_data_directory }}/config/provisioning/dashboards"

- name: InfluxDB
  docker_container:
    name: influxdb
    networks:
      - name: "{{ nas_bridge_network }}"
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: influxdb:1.8
    pull: true
    volumes:
      - "{{ influxdb_data_directory }}:/var/lib/influxdb:rw"
    ports:
      - "{{ grafana_influxdb_port }}:8086"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    env:
      INFLUXDB_LOGGING_LEVEL: "error"
    memory: 1g

- name: hddtemp
  docker_container:
    name: hddtemp
    networks:
      - name: "{{ nas_bridge_network }}"
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: drewster727/hddtemp-docker
    pull: true
    privileged: true
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    env:
      HDDTEMP_ARGS: "-q -d -F /dev/sd*"
      TZ: "{{ ansible_nas_timezone }}"
    memory: 128m

- name: Template telegraf.conf
  template:
    src: telegraf/telegraf.conf
    dest: "{{ telegraf_data_directory }}/telegraf.conf"

- name: Telegraf
  docker_container:
    name: telegraf
    networks:
      - name: "{{ nas_bridge_network }}"
        links:
          - hddtemp:hddtemp
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: telegraf
    pull: true
    privileged: true
    ipc_mode: host
    volumes:
      - "{{ telegraf_data_directory }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/:/hostfs:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/sys:/hostfs/sys:ro"
      - "/var:/hostfs/var:ro"
      - "/run:/hostfs/run:ro"
    env:
      HOST_ETC: "/hostfs/etc"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_VAR: "/hostfs/var"
      HOST_RUN: "/hostfs/run"
      HOST_MOUNT_PREFIX: "/hostfs"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g

- name: Template grafana.ini
  template:
    src: grafana/grafana.ini
    dest: "{{ grafana_data_directory }}/etc/grafana.ini"

- name: Template Grafana data source
  template:
    src: grafana/provisioning/datasources/ansible-nas.yml
    dest: "{{ grafana_data_directory }}/config/provisioning/datasources/ansible-nas.yml"

- name: Copy Ansible-NAS Dashboard Provisioner
  copy:
    src: grafana/provisioning/dashboards/ansible-nas.yml
    dest: "{{ grafana_data_directory }}/config/provisioning/dashboards/ansible-nas.yml"

- name: Copy Ansible-NAS Dashboard
  copy:
    src: grafana/dashboards/ansible-nas/ansible-nas-overview.json
    dest: "{{ grafana_data_directory }}/data/dashboards/ansible-nas/ansible-nas-overview.json"

- name: Grafana
  docker_container:
    name: grafana
    networks:
      - name: "{{ nas_bridge_network }}"
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: grafana/grafana
    pull: true
    volumes:
      - "{{ grafana_data_directory }}/data:/var/lib/grafana:rw"
      - "{{ grafana_data_directory }}/config/provisioning:/etc/grafana/provisioning:ro"
      - "{{ grafana_data_directory }}/etc/grafana.ini:/etc/grafana/grafana.ini:rw"
    # ports:
    #   - "{{ grafana_port }}:3000"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g
    env:
#      GF_LOG_LEVEL: debug
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,camptocamp-prometheus-alertmanager-datasource"
    labels:
      traefik.enable: "{{ grafana_available_externally }}"
      traefik.http.routers.grafana.entrypoints: "web,websecure"
      traefik.http.routers.grafana.rule: "Host(`{{ grafana_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.grafana.tls.certresolver: "letsencrypt"
      traefik.http.routers.grafana.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.grafana.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      # Middleware to set the Content-Security-Policy header
      traefik.http.middlewares.csp-headers.headers.customResponseHeaders.Content-Security-Policy: "frame-ancestors organizr.shazbot.one"
      # Attach the middleware to the router
      traefik.http.routers.grafana.middlewares: "csp-headers"    
      autoheal: "true"
