---
- name: Create Virtual Desktop Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ vd_data_directory }}"
    - "{{ vd_data_directory }}/home"

- name: Create users file
  template:
    src: "templates/virtual_desktop/users.txt.j2"
    dest: "{{ vd_data_directory }}/users.txt"

- name: Virtual Desktop Container
  docker_container:
    name: virtual_desktop
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: "{{ vd_docker_image }}"
    pull: true
    volumes:
      - "{{ vd_data_directory }}/users.txt:/root/createusers.txt:ro"
      - "{{ vd_data_directory }}/home:/home:rw"
      - "{{ samba_shares_root }}:/samba:rw"
      - "{{ docker_home }}:/docker:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ vd_rdp_port }}:3389"
    privileged: true
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 2g
