---
- name: Create linkwarden Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ linkwarden_user_id }}"
  with_items:
    - "{{ linkwarden_data_directory }}"
    - "{{ linkwarden_data_directory }}/data"
    - "{{ linkwarden_data_directory }}/pgdata"
    - "{{ linkwarden_data_directory }}/meili_data"

- name: Setup linkwarden docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ role_path }}/docker-compose.yml"


- name: Run docker compose pull
  shell: "docker compose pull --ignore-pull-failures || true"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- name: Run docker compose build
  shell: "docker compose build"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- debug: var=shell_output.stdout

- name: Deploy linkwarden Docker Compose stack
  community.docker.docker_compose_v2:
    remove_orphans: true
    recreate: "{{ 'always' if docker_recreate else 'auto' }}"
    project_src: "{{ role_path }}"
    files:
      - docker-compose.yml
  register: shell_output

- name: Remove docker-compose.yml
  file:
    path: "{{ role_path }}/docker-compose.yml"
    state: absent
