---
#- name: build expressvpn image
#  docker_image:
#    name: myexpressvpn
#    build:
#      path: "{{ role_path }}/files/"
#    buildargs:
#      UID: "{{ owncloud_user_id }}"
#      GID: "{{ owncloud_group_id }}"
#    source: build
#    state: present
#    rm: yes
#    force: yes

- name: ExpressVPN
  docker_container:
    name: expressvpn
    image: misioslav/expressvpn:3.68.0.2
    pull: true
    networks:
      - name: "{{ nas_bridge_network }}"
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    #    dns_servers:
    #      - 1.1.1.1
    #      - 1.0.0.1
    volumes:
      - "/dev/net/tun:/dev/net/tun:z"
      #   ports:
      #     - 51413:51413
      #     - 51413:51413/udp
    memory: 1g
    etc_hosts: "{ \n  \"{{ sabnzbd_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ transmission_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ jackett_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ bazarr_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ sonarr_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ radarr_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ lidarr_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ mylar_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ webhookd_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ static_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ plex_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ emby_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\",\n  \"{{ subsonic_hostname }}.{{ ansible_nas_domain }}\": \"{{ nas_ip }}\"\n}\n"
    env:
      WHITELIST_DNS: "{{ expressvpn_whitelist_dns }}"
      SERVER: "SMART"
      CODE: "{{ secret.expressvpn_code }}"
      DDSN: "{{ ansible_nas_hostname }}.{{ ansible_nas_domain }}"
      NETWORK: "on"
    tty: true
    #    interactive: true
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true
    labels:
      com.centurylinklabs.watchtower.enable: "false"
