---
#- name: build expressvpn image
#  docker_image:
#    name: myexpressvpn
#    build:
#      path: "{{ role_path }}/files/"
#    buildargs:
#      UID: "{{ owncloud_user_id }}"
#      GID: "{{ owncloud_group_id }}"
#    source: build
#    state: build
#    rm: yes
#    force: yes

- name: ExpressVPN
  docker_container:
    name: expressvpn
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: 1
#    image: myexpressvpn:latest
    image: misioslav/expressvpn:latest
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
#    dns_servers:
#      - 1.1.1.1
#      - 1.0.0.1
    volumes:
      - "/dev/net/tun:/dev/net/tun:z"
    ports:
      - 51413:51413
      - 51413:51413/udp
    memory: 1g
    etc_hosts: >
      { 
        "{{ sabnzbd_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ transmission_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ jackett_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ bazarr_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ sonarr_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ radarr_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ lidarr_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ mylar_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ webhookd_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ static_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ plex_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ emby_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}",
        "{{ subsonic_hostname }}.{{ ansible_nas_domain }}": "{{ nas_ip }}"
      }
    env:
      WHITELIST_DNS: "{{ expressvpn_whitelist_dns }}"
      SERVER: "SMART"
      CODE: "{{ secret.expressvpn_code }}"
      DDSN: "{{ ansible_nas_hostname }}.{{ ansible_nas_domain }}"
      NETWORK: "on"
    tty: true
#    interactive: true
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true
    labels:
      autoheal: "true"
      com.centurylinklabs.watchtower.enable: "false"

