---
- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ heimdall_data_directory }}"

- name: Create Heimdall container
  docker_container:
    name: heimdall
    image: "{{ heimdall_docker_image }}"
    pull: true
    volumes:
      - "{{ heimdall_data_directory }}:/config:rw"
    env:
      PUID: "{{ jellyfin_user_id }}"
      PGID: "{{ jellyfin_group_id }}"
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ heimdall_port_http }}:80"
      - "{{ heimdall_port_https }}:443"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "heimdall"
      traefik.frontend.rule: "Host:heimdall.{{ ansible_nas_domain }}"
      traefik.enable: "{{ heimdall_available_externally }}"
      traefik.port: "80"