---
# External Access
# Traefik will allow access to certain applications externally. To enable this you'll either; a domain name that points to your
# home static IP address, the cloudflare with the cloudflare_ddns dynamic DNS container enabled, or use a dynamic DNS provider like no-ip.
# You'll also need to map ports 80 and 443 from your router to your ansible-nas server, then enable the per-app "available_externally"
# settings.
traefik_enabled: false

# directories
traefik_data_directory: "{{ docker_home }}/traefik"

# network
traefik_port_http: "80"
traefik_port_https: "443"
traefik_port_ui: "8083"

traefik_docker_image: traefik:v2.3
traefik_log_level: "INFO"

# find the relevant name and environment variables for your DNS provider at https://go-acme.github.io/lego/dns/
traefik_dns_provider: cloudflare
traefik_environment_variables:
  CF_API_EMAIL: "{{ ansible_nas_email }}"
  CF_API_KEY: "abcdeabcdeabcdeabcde1234512345"
# traefik_acme_server: "https://acme-staging-v02.api.letsencrypt.org/directory" # staging
traefik_acme_server: "https://acme-v02.api.letsencrypt.org/directory" # production
