---
- name: Create readarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ readarr_data_directory }}"

- name: readarr
  docker_container:
    name: readarr
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: lscr.io/linuxserver/readarr:develop
    pull: true
    volumes:
      - "{{ readarr_books_directory }}:/books:rw"
      - "{{ readarr_audio_books_directory }}:/audiobooks:rw"
      - "{{ readarr_data_directory }}:/config:rw"
      - "{{ readarr_download_directory }}:/downloads:rw"
#    ports:
#      - "{{ readarr_port }}:6767"
    network_mode: "{{ 'container:' + proxy_container if readarr_proxy else 'None' }}"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ readarr_user_id }}"
      PGID: "{{ readarr_group_id }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g
    healthcheck:
      test: ["CMD", "curl", "--fail", "-4", "{{ health_check_url }}"]
      interval: 1m
      timeout: 5s
      retries: 2
      start_period: 90s
    labels:
      traefik.enable: "{{ readarr_available_externally }}"
      traefik.http.routers.readarr.entrypoints: "web,websecure"
      traefik.http.routers.readarr.rule: "Host(`{{ readarr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.readarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.readarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.readarr.loadbalancer.server.port: "8787"
      autoheal: "true"
      # traefik.http.routers.readarr.middlewares: do-auth"
      # traefik.http.middlewares.do-auth.basicauth.users: "{{ traefik_auth }}"
