---
- name: MuxiMux
  docker_container:
    image: linuxserver/muximux
    name: muximux
    log_driver: 'json-file'
    log_options:
      max-file: '5'
      max-size: '10m'
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ muximux_user_id }}"
      PGID: "{{ muximux_group_id }}"
    volumes:
      - "{{ muximux_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.enable: "{{ muximux_available_externally }}"
      traefik.http.routers.muximux.rule: "Host(`{{ muximux_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.muximux.tls.certresolver: "letsencrypt"
      traefik.http.routers.muximux.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.muximux.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.muximux.loadbalancer.server.port: "80"
    ports:
      - "{{ muximux_port }}:80"
    restart_policy: unless-stopped
    memory: 512m
