---
- name: MuxiMux
  docker_container:
    name: muximux
    log_driver: 'json-file'
    log_options:
      max-size: 256m
      max-file: "1"
    image: linuxserver/muximux
    networks:
      - name: "{{ nas_bridge_network }}"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ muximux_user_id }}"
      PGID: "{{ muximux_group_id }}"
    volumes:
      - "{{ muximux_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.enable: "{{ muximux_available_externally }}"
      traefik.http.routers.muximux.entrypoints: "web,websecure"
      traefik.http.routers.muximux.rule: "Host(`{{ muximux_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.muximux.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.muximux.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.muximux.loadbalancer.server.port: "80"
#    ports:
#      - "{{ muximux_port }}:80"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 128m
