---
- name: Create Airsonic Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ airsonic_data_directory }}/data"

- name: Airsonic Docker Container
  docker_container:
    name: airsonic
    log_options:
      max-size: 256m
      max-file: 1
    image: linuxserver/airsonic:latest
    pull: true
    volumes:
      - "{{ airsonic_data_directory }}/data:/config:rw"
      - "{{ airsonic_playlist_directory }}:/playlists:rw"
      - "{{ airsonic_music_directory }}:/music:rw"
      - "{{ airsonic_books_directory }}:/books:rw"
      - "{{ airsonic_podcasts_directory }}:/podcasts:rw"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ airsonic_user_id }}"
      PGID: "{{ airsonic_group_id }}"
    ports:
      - "{{ airsonic_port }}:4040"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g
    labels:
      traefik.enable: "{{ airsonic_available_externally }}"
      traefik.http.routers.airsonic.entrypoints: "web,websecure"
      traefik.passHostHeader: "true"
      traefik.http.routers.airsonic.rule: "Host(`{{ airsonic_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.airsonic.tls.certresolver: "letsencrypt"
      traefik.http.routers.airsonic.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.airsonic.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.airsonic.loadbalancer.server.port: "4040"

- name: airsonic-frontend
  docker_container:
    name: airsonic-frontend
    log_options:
      max-size: 256m
      max-file: 1
    image: tamland/airsonic-frontend:latest
    pull: true
    env:
      TZ: "{{ ansible_nas_timezone }}"
      SERVER_URL: "https://{{ airsonic_hostname }}.{{ ansible_nas_domain }}"
    ports:
      - "{{ airsonic_fe_port }}:80"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 256m
    labels:
      traefik.enable: "true"
      traefik.passHostHeader: "true"
      traefik.http.routers.sonicfe.rule: "Host(`{{ airsonic_fe_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.services.sonicfe.loadbalancer.server.port: "80"

