---
watchtower_enabled: false

# Sets the 6 field cron schedule to use for checks and updates. This will check at 12pm on thrusday.
watchtower_cron_schedule: 0 0 12 * * THU

# Sets the Watchtower Docker start command. Different options can be supplied based on whether you want to receive
# notifications or not, some examples are provided below. See https://containrrr.dev/watchtower/arguments/ for more options.

# No notifications
# watchtower_command: "--schedule '{{ watchtower_cron_schedule }}'"


# Slack notifications
# watchtower_command: "--schedule '{{ watchtower_cron_schedule }}' --notifications 'slack' --notification-slack-hook-url 'https://hooks.slack.com/services/xxx/yyyyyyyyyyyyyyy' 
#   --notification-slack-identifier 'ansible-nas'"
