---
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 65536
    write: 65536

log:
  level: info
  file_path: /logs/authelia.log
  format: json
  keep_stdout: true

theme: dark
default_redirection_url: https:/{{ authelia_hostname }}.{{ ansible_nas_domain }}

totp:
  issuer: authelia.com

#docker run authelia/authelia:latest authelia hash-password 'yourpassword'
authentication_backend:
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control:
  default_policy: two_factor
  networks:
  # - name: internal
  #   networks:
  #   - 192.168.1.0/24
  rules:
    - domain: "*.{{ ansible_nas_domain }}"
      policy: two_factor
session:
  name: authelia_session
  expiration: 30d  # 1 h
  inactivity: 5d  # 5 day
  domain: {{ ansible_nas_domain }}  # Should match whatever your root protected domain is
  remember_me_duration:  30d
  redis:
    host: authelia_redis
    port: 6379

regulation:
  max_retries: 5
  find_time: 120m
  ban_time: 300m

storage:
  local:
    path: /config/db.sqlite3

notifier:
#Internal SMTP forwarder.
  # smtp:
    # host: mail.{{ ansible_nas_domain }}
    # port: 26
    # sender: mymail@gmail.com
    # disable_require_tls: true
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  filesystem:
    filename: /logs/notification.txt

#Local NTP server on the router
# ntp:
#   address: "192.168.1.1:123"
#   version: 3
#   max_desync: 3s
#   disable_startup_check: false
#   disable_failure: false
