---
- name: varken
  docker_container:
    name: varken
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: boerderij/varken
    networks:
      - name: "{{ nas_bridge_network }}"
        links:
          - influxdb:influxdb
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ varken_user_id }}"
      PGID: "{{ varken_group_id }}"
    volumes:
      - "{{ varken_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 128m
