---
- name: varken
  docker_container:
    image: boerderij/varken
    name: varken
    log_driver: 'json-file'
    log_options:
      max-file: '5'
      max-size: '10m'
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ varken_user_id }}"
      PGID: "{{ varken_group_id }}"
    volumes:
      - "{{ varken_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate | default('no') }}"
    memory: 128m
    links:
        - influxdb:influxdb
