---
- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ transmission_download_directory }}"
    - "{{ transmission_watch_directory }}"

- name: Transmission Docker Container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    pull: true
    volumes:
      - "{{ transmission_config_directory }}:/config:rw"
      - "{{ transmission_download_directory }}:/downloads:rw"
      - "{{ transmission_watch_directory }}:/watch:rw"
    env:
      TZ: "{{ transmission_timezone }}"
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
    restart_policy: unless-stopped
    network_mode: "{{ 'container:' + proxy_container if sabnzbd_proxy else 'None' }}"
    memory: 1g
    healthcheck:
      test: ["CMD", "curl", "--fail", "-4", "{{ health_check_url }}"]
      interval: 1m
      timeout: 5s
      retries: 2
      start_period: 90s
