---
- name: build subsonic image
  docker_image:
    name: subsonic
    build:
      path: "{{ role_path }}/files/"
    buildargs:
      UID: "{{ subsonic_user_id }}"
      GID: "{{ subsonic_group_id }}"
    source: build
    state: build
    rm: yes
    force: yes

- name: Subsonic Docker Container
  docker_container:
    name: subsonic
    log_options:
      max-size: 256m
      max-file: "1"
    image: subsonic
    volumes:
      - "{{ subsonic_music_directory }}:/music:rw"
      - "{{ subsonic_books_directory }}:/books:rw"
      - "{{ subsonic_podcasts_directory}}:/podcasts:rw"
      - "{{ subsonic_playlists_directory }}:/playlists:rw"
      - "{{ subsonic_data_directory }}:/data:rw"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ subsonic_user_id }}"
      PGID: "{{ subsonic_group_id }}"
    user: "{{ subsonic_user_id }}"
    memory: 2g
    ports:
      - "{{ subsonic_port }}:4141"
    labels:
      traefik.enable: "{{ subsonic_available_externally }}"
#      traefik.http.middlewares.subsonic.redirectscheme.scheme: "https"
#      traefik.http.middlewares.subsonic.redirectscheme.permanent: "true"
#      traefik.http.middlewares.subsonic.headers.sslproxyheaders.X-Forwarded-Proto: "https"
#      traefik.http.routers.subsonic.middlewares: "subsonic@docker"
      traefik.passHostHeader: "true"
      traefik.http.routers.subsonic.entrypoints: "websecure,websecure-ext"
      traefik.http.routers.subsonic.rule: "Host(`{{ subsonic_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.subsonic.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.subsonic.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.subsonic.loadbalancer.server.port: "4141"
      traefik.http.services.subsonic.loadbalancer.server.scheme: "https"
      com.centurylinklabs.watchtower.enable: "false"
      autoheal: "true"


