---
- name: umi Docker Container
  docker_container:
    name: umi
    log_options:
      max-size: 256m
      max-file: "1"
    image: phynias/umi:latest
    pull: true
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    restart_policy: unless-stopped
    env:
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      autoheal: "true"
      traefik.enable: "{{ umi_available_externally }}"
      traefik.http.routers.umi.entrypoints: "web,websecure"
      traefik.http.routers.umi.rule: "Host(`{{ umi_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.umi.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.umi.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.umi.loadbalancer.server.port: "8080"
