---
papermerge_enabled: false
papermerge_available_externally: "false"

# directories
papermerge_data_directory: "{{ docker_home }}/papermerge"

# uid / gid
papermerge_user_id: "0"
papermerge_group_id: "0"

# network
papermerge_port: "8000"
papermerge_hostname: "papermerge"
papermerge_secret: ""
papermerge_password: ""
