---
- name: Create Organizr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ organizr_data_directory }}"

- name: Create Organizr container
  docker_container:
    name: organizr
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: organizr/organizr:latest
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes:
      - "{{ organizr_data_directory }}:/config:rw"
    env:
      PUID: "{{ organizr_user_id }}"
      PGID: "{{ organizr_group_id }}"
      TZ: "{{ ansible_nas_timezone }}"
      branch: "v2-master"
#    ports:
#      - "{{ organizr_port_http }}:80"
#      - "{{ organizr_port_https }}:443"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 256m
    labels:
      traefik.enable: "{{ organizr_available_externally }}"
      traefik.http.routers.organizr.entrypoints: "web,websecure"
      traefik.http.routers.organizr.rule: "Host(`{{ organizr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.organizr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.organizr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.organizr.loadbalancer.server.port: "80"
      autoheal: "true"
