---
- name: Create monitorr Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ monitorr_data_directory }}"
- name: monitorr Docker Container
  docker_container:
    name: monitorr
    image: monitorr/monitorr
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes:
      - "{{ monitorr_data_directory }}:/app"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PGID: "{{ monitorr_user_id }}"
      PUID: "{{ monitorr_group_id }}"
    labels:
      traefik.enable: "{{ monitorr_available_externally }}"
      traefik.http.routers.monitorr.entrypoints: "websecure,web"
      traefik.http.routers.monitorr.rule: "Host(`{{ monitorr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.monitorr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.monitorr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.monitorr.loadbalancer.server.port: "80"
      traefik.http.routers.monitorr.middlewares: "{{ port|default(omit) if nas_auth_middleware is not defined else nas_auth_middleware }}"
