---
- name: Create Bazarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bazarr_data_directory }}"

- name: Bazarr
  docker_container:
    name: bazarr
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: linuxserver/bazarr:development
    pull: true
    volumes:
      - "{{ bazarr_tv_directory }}:/tv:rw"
      - "{{ bazarr_movies_directory }}:/movies:rw"
      - "{{ bazarr_data_directory }}:/config:rw"
#    ports:
#      - "{{ bazarr_port }}:6767"
    network_mode: "{{ 'container:' + proxy_container if bazarr_proxy else 'None' }}"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ bazarr_user_id }}"
      PGID: "{{ bazarr_group_id }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 1g
    healthcheck:
      test: ["CMD", "curl", "--fail", "-4", "{{ health_check_url }}"]
      interval: 1m
      timeout: 5s
      retries: 2
      start_period: 90s
    labels:
      traefik.enable: "{{ bazarr_available_externally }}"
      traefik.http.routers.bazarr.entrypoints: "web,websecure"
      traefik.http.routers.bazarr.rule: "Host(`{{ bazarr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.bazarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.bazarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
      traefik.http.routers.bazarr.middlewares: "{{ port|default(omit) if nas_auth_middleware is not defined else nas_auth_middleware }}"
      autoheal: "true"
      # traefik.http.routers.bazarr.middlewares: do-auth"
      # traefik.http.middlewares.do-auth.basicauth.users: "{{ traefik_auth }}"
