---
- name: Set login banner
  copy:
    src: motd.txt
    dest: /etc/motd

- name: ensuring Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  apt_repository:
    repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
    state: present
  when: >
        ansible_distribution_version >= '16.04'


- name: Enable universe repository
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}  universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
  register: add_repo_result

- debug: var=add_repo_result

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages
  apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  apt:
    name: "{{ ansible_nas_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

#  - name: Configure smartmontools

- name: "Set hostname to {{ ansible_nas_hostname }}"
  hostname:
    name: "{{ ansible_nas_hostname }}"

- name: "Set timezone to {{ ansible_nas_timezone }}"
  timezone:
    name: "{{ ansible_nas_timezone }}"

#- name: "Permission share directories"
#  file:
#    path: "{{ item.path }}"
#    state: directory
#    owner: nasuser
#    group: root
#    mode: "u=rwX,g=rwX,o=rX"
#    recurse: false
#  loop: "{{ samba_shares }}"
