---
- name: Create tandoor Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tandoor_data_directory }}"
    - "{{ tandoor_data_directory }}/postgresql"
    - "{{ tandoor_data_directory }}/staticfiles"
    - "{{ tandoor_data_directory }}/nginx"
    - "{{ tandoor_data_directory }}/mediafiles"

- name: Setup tandoor docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ role_path }}/docker-compose.yml"

- name: Run docker compose pull
  shell: "docker compose pull --ignore-pull-failures || true"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- name: Run docker compose build
  shell: "docker compose build"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- debug: var=shell_output.stdout

- name: Deploy tandoor Docker Compose stack
  community.docker.docker_compose_v2:
    remove_orphans: true
    recreate: "{{ 'always' if docker_recreate else 'auto' }}"
    project_src: "{{ role_path }}"
    files:
    - docker-compose.yml
  register: shell_output
