---
- name: Create papermerge Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ papermerge_data_directory }}"
    - "{{ papermerge_data_directory }}/media"
    - "{{ papermerge_data_directory }}/redis"
- name: redis
  docker_container:
    name: papermerge_redis
    image: webhippie/redis:latest
    networks:
      - name: "{{ nas_bridge_network }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    env:
      REDIS_DATABASES: "1"
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "{{ papermerge_data_directory }}/redis:/var/lib/redis"
    memory: 64m
- name: papermerge
  docker_container:
    name: papermerge
    image: papermerge/papermerge:3.0.3
    networks:
      - name: "{{ nas_bridge_network }}"
        links:
          - "papermerge_redis:redis"
    pull: true
    volumes:
      - "{{ papermerge_data_directory }}/media:/app/media:rw"
    env:
      PAPERMERGE__SECURITY__SECRET_KEY: "{{ papermerge_secret }}"
      PAPERMERGE__AUTH__PASSWORD: "{{ papermerge_password }}"
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ papermerge_user_id }}"
      PGID: "{{ papermerge_group_id }}"
      REDIS_URL: "redis"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    labels:
      traefik.enable: "{{ papermerge_available_externally }}"
      traefik.http.routers.papermerge.entrypoints: "websecure,web"
      traefik.http.routers.papermerge.rule: "Host(`{{ papermerge_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.papermerge.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.papermerge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.papermerge.loadbalancer.server.port: "80"
