---
- name: Create papermerge Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ papermerge_data_directory }}"
    - "{{ papermerge_data_directory }}/media"

- name: papermerge
  register: docker_container_output
  docker_container:
    name: papermerge
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: papermerge/papermerge:latest
    pull: true
    links:
      - "redis:redis"
    volumes:
      - "{{ papermerge_data_directory }}/media:/app/media:rw"
    env:
      PAPERMERGE__MAIN__SECRET_KEY: "{{ papermerge_secret }}"
      DJANGO_SUPERUSER_PASSWORD: "{{ papermerge_password }}"
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ papermerge_user_id }}"
      PGID: "{{ papermerge_group_id }}"
      REDIS_URL: "redis"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    labels:
      traefik.enable: "{{ papermerge_available_externally }}"
      traefik.http.routers.papermerge.entrypoints: "web,websecure"
      traefik.http.routers.papermerge.rule: "Host(`{{ papermerge_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.papermerge.tls.certresolver: "letsencrypt"
      traefik.http.routers.papermerge.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.papermerge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.papermerge.loadbalancer.server.port: "8000"
      autoheal: "true"
