---
- name: Sabnzbd
  docker_container:
    name: sabnzbd
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: 1
    image: linuxserver/sabnzbd
    pull: true
    volumes:
      - "{{ sabnzbd_download_directory }}:/downloads:rw"
      - "{{ sabnzbd_watch_directory }}:/watch:rw"
      - "{{ sabnzbd_config_directory }}:/config:rw"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ sabnzbd_user_id }}"
      PGID: "{{ sabnzbd_group_id }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    network_mode: "{{ 'container:' + proxy_container if sabnzbd_proxy else 'None' }}"
    memory: 1.5g
    healthcheck:
      test: ["CMD", "curl", "--fail", "-4", "{{ health_check_url }}"]
      interval: 1m
      timeout: 5s
      retries: 2
      start_period: 90s
    labels:
      traefik.enable: "{{ sabnzbd_available_externally }}"
      traefik.http.routers.sabnzbd.entrypoints: "web,websecure"
      traefik.passHostHeader: "true"
      traefik.http.routers.sabnzbd.rule: "Host(`{{ sabnzbd_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.sabnzbd.tls.certresolver: "letsencrypt"
      traefik.http.routers.sabnzbd.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.sabnzbd.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
      autoheal: "true"
