---
- name: Create prometheus Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_data_directory }}"

- name: prometheus.yml;
  template: 
    src: prometheus.yml.j2
    dest: "{{prometheus_data_directory }}/prometheus.yml"
  notify:
    - restart prometheus

- name: node_exporter
  docker_container:
    pid_mode: host
    pull: true
    name: node-exporter
    image: prom/node-exporter
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate | default('no') }}"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
      - "--collector.zfs"

# - name: zfs_exporter
#   docker_container:
#     pid_mode: host
#     pull: true
#     name: zfs-exporter
#     image: derekgottlieb/zfs-exporter
#     restart_policy: unless-stopped
#     privileged: true  

- name: cadvisor
  docker_container:
    image: gcr.io/google-containers/cadvisor
    name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    recreate: "{{ 'yes' if docker_recreate | default('no') }}"
    restart_policy: unless-stopped

- name: prometheus
  docker_container:
    image: prom/prometheus
    name: prometheus
    pull: true
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - --storage.tsdb.retention.time=1y
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "{{ prometheus_port }}:9090"
    volumes:
      - "{{ prometheus_data_directory }}/data:/prometheus"
      - "{{ prometheus_data_directory }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_directory }}/rules:/etc/prometheus/rules"
    recreate: "{{ 'yes' if docker_recreate | default('no') }}"
    restart_policy: unless-stopped
    memory: 512m
    user: "{{ nas_uid }}:{{ nas_gid }}"
    links:
      - "grafana"
      - "node-exporter"
      - "cadvisor"
#      - "zfs-exporter"

