---
- name: Create prometheus Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_data_directory }}"
- name: prometheus.yml;
  template:
    src: prometheus.yml.j2
    dest: "{{prometheus_data_directory }}/prometheus.yml"
  notify:
    - restart prometheus
- name: blackbox.yml;
  template:
    src: blackbox.yml.j2
    dest: "{{prometheus_data_directory }}/blackbox.yml"
  notify:
    - restart blackbox
- name: node_exporter
  docker_container:
    pid_mode: host
    pull: true
    name: node-exporter
    image: prom/node-exporter
    networks:
      - name: "{{ nas_bridge_network }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    force_kill: true
    volumes:
      - "{{ prometheus_data_directory }}/textcollector:/textcollector"
      - "/etc/timezone:/etc/timezone:ro"
      - "/:/rootfs:ro,rslave"
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.textfile.directory=/textcollector"
      - "--collector.zfs"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    memory: 64m
- name: blackbox
  docker_container:
    name: blackbox
    pull: true
    image: prom/blackbox-exporter:latest
    networks:
      - name: "{{ nas_bridge_network }}"
    volumes:
      - "{{ prometheus_data_directory }}/blackbox.yml:/etc/blackbox_exporter/config.yml"
      #    ports:
      #      - 9115:9115
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    force_kill: true
- name: alertmanager
  docker_container:
    name: alertmanager
    image: prom/alertmanager
    networks:
      - name: "{{ nas_bridge_network }}"
    ports:
      - 9093:9093
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ prometheus_data_directory }}/alertmanager/storage:/alertmanager"
      - "{{ prometheus_data_directory }}/alertmanager/etc:/etc/alertmanager"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    force_kill: true
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - "--web.external-url=http://192.168.1.200:9393/"
      #      - "--web.hostname="
    memory: 64m
    user: "{{ nas_uid }}:{{ nas_gid }}"
# - name: zfs_exporter
#   docker_container:
#     pid_mode: host
#     pull: true
#     name: zfs-exporter
#     image: derekgottlieb/zfs-exporter
#     restart_policy: unless-stopped
#     privileged: true  
- name: cadvisor
  docker_container:
    name: cadvisor
    image: gcr.io/google-containers/cadvisor
    networks:
      - name: "{{ nas_bridge_network }}"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    force_kill: true
    restart_policy: unless-stopped
    command:
      - --allow_dynamic_housekeeping=true
      - --housekeeping_interval=30s
      - --global_housekeeping_interval=2m
      - --disable_metrics=disk,tcp,udp
      - --docker_only=true
    memory: 1g
#- name: loki
#  docker_container:
#    name: loki
#    pull: true
#    image: grafana/loki
#    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
#    force_kill: true
#    restart_policy: unless-stopped
#    command: 
#      - "-config.file=/etc/loki/loki-local-config.yaml"
#    ports:
#      - "3100:3100"
#    volumes:
#      - "/etc/timezone:/etc/timezone:ro"
#      - "{{ prometheus_data_directory }}/loki/data:/data/loki"
#      - "{{ prometheus_data_directory }}/loki/etc/loki-local-config.yaml:/etc/loki/loki-local-config.yaml"
#    user: "{{ nas_uid }}:{{ nas_gid }}"
#    healthcheck:
#      test: ["CMD", "wget", "--spider", "-S", "http://localhost:3100/ready"]
#      start_period: 1m
#    labels:
#      autoheal: "true"
- name: promtail
  docker_container:
    name: promtail
    pull: true
    image: grafana/promtail
    networks:
      - name: "{{ nas_bridge_network }}"
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    force_kill: true
    restart_policy: unless-stopped
    command:
      - "-config.file=/mnt/config/promtail-config.yaml"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/zpool1/docker/traefik/logs/:/logs/traefik"
      - "{{ prometheus_data_directory }}/promtail/etc/promtail-config.yaml:/mnt/config/promtail-config.yaml"
      - "{{ prometheus_data_directory }}/promtail/cache:/cache"
    user: "{{ nas_uid }}:{{ nas_gid }}"
- name: prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus
    networks:
      - name: "{{ nas_bridge_network }}"
        links:
          - "grafana"
          - "node-exporter"
          - "cadvisor"
          - "alertmanager"
          #          - "loki"
    user: "{{ nas_uid }}:{{ nas_gid }}"
    pull: true
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1y"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.external-url=http://192.168.1.200:9393/"
    ports:
      - "{{ prometheus_port }}:9090"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ prometheus_data_directory }}/data:/prometheus"
      - "{{ prometheus_data_directory }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_directory }}/rules:/etc/prometheus/rules"
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    force_kill: true
    restart_policy: unless-stopped
    memory: 1g
- name: Grab latest smartmon.sh
  get_url:
    url: https://raw.githubusercontent.com/olegeech-me/S.M.A.R.T-disk-monitoring-for-Prometheus/master/smartmon.sh
    dest: /usr/local/bin/smartmon.sh
    mode: 0755
    group: root
    owner: root
- name: Setup cron
  cron:
    name: "Smartmon to textcollector"
    user: "root"
    minute: "*"
    hour: "*"
    job: "/usr/local/bin/smartmon.sh > {{ prometheus_data_directory }}/textcollector/smart_metrics.prom"
