
---
- name: Create Ombi Directories
  file:
    path: "{{ ombi_config_directory }}"
    state: directory

- name: Ombi Docker Container
  docker_container:
    name: ombi
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: linuxserver/ombi:development
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes:
      - "{{ ombi_config_directory }}:/config:rw"
    publish_all_ports: false
#    ports:
#      - "{{ ombi_port }}:3579"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ ombi_user_id }}"
      PGID: "{{ ombi_group_id }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    labels:
      traefik.enable: "{{ ombi_available_externally }}"
      traefik.http.routers.ombi.entrypoints: "websecure,websecure-ext"
      traefik.http.routers.ombi.rule: "Host(`{{ ombi_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.ombi.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.ombi.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.ombi.loadbalancer.server.port: "3579"
