---
- name: Create uptimekuma Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ uptimekuma_data_directory }}"
- name: uptimekuma Docker Container
  docker_container:
    name: uptimekuma
    image: louislam/uptime-kuma:latest
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes:
      - "{{ uptimekuma_data_directory }}:/app/data"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    memory: 512m
    env:
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.enable: "{{ uptimekuma_available_externally }}"
      traefik.http.routers.uptimekuma.entrypoints: "websecure,web"
      traefik.http.routers.uptimekuma.rule: "Host(`{{ uptimekuma_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.uptimekuma.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.uptimekuma.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.uptimekuma.loadbalancer.server.port: "3001"
      # Middleware to set the Content-Security-Policy header
      traefik.http.middlewares.csp-headers.headers.customResponseHeaders.Content-Security-Policy: "frame-ancestors organizr.shazbot.one"
      # Attach the middleware to the router
      traefik.http.routers.uptimekuma.middlewares: "csp-headers"
