---
- name: Create graylog Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ graylog_data_directory }}/mongodb"
    - "{{ graylog_data_directory }}/config"
    - "{{ graylog_data_directory }}/data"
    - "{{ graylog_data_directory }}/opensearch"

- name: Setup graylog config.conf
  template:
    src: templates/graylog.conf.j2
    dest: "{{ graylog_data_directory }}/config/graylog.conf"

- name: Setup graylog docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ role_path }}/docker-compose.yml"

- name: Run docker compose pull
  shell: "docker compose pull --ignore-pull-failures || true"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- name: Run docker compose build
  shell: "docker compose build"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- debug: var=shell_output.stdout

- name: Deploy graylog Docker Compose stack
  community.docker.docker_compose_v2:
    remove_orphans: true
    recreate: "{{ 'always' if docker_recreate else 'auto' }}"
    project_src: "{{ role_path }}"
    files:
    - docker-compose.yml
  register: shell_output

- name: Remove docker-compose.yml
  file:
    path: "{{ role_path }}/docker-compose.yml"
    state: absent
