http:
  middlewares:

    basic_auth:
      basicauth:
        users:
          - "{{ wyze_local_user }}:{{ wyze_local_pass }}"
        removeheader: true
      ipWhiteList:
        sourceRange:
          - "172.17.0.0/16"
          - "127.0.0.1"
          - "192.168.1.200"

    onlyLocalNetwork:
      ipWhiteList:
        sourceRange:
          - "192.168.1.0/24"
#        ipstrategy:
#          depth: 2

        ipstrategy:
          excludedips:
            - "192.168.1.1"

    google-oauth:
      forwardAuth:
        address: "https://oauth.shazbot.one" # Make sure you have the OAuth service in docker-compose.yml
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"




