http:
  middlewares:

    onlyLocalNetwork:
      ipWhiteList:
        sourceRange:
          - "192.168.1.0/24"
#        ipstrategy:
#          depth: 2

        ipstrategy:
          excludedips:
            - "192.168.1.1"
