auth:
  globalToken: "{{ cloudflare_api_key }}"
  email: "{{ cloudflare_email }}"
domains:
  - name: "{{ cloudflare_host }}"
    type: A
    proxied: false
    create: true
    zoneName: "{{ cloudflare_zone }}"
