- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"
    - "{{ homeassistant_data_directory }}/mariadb"


- name: Setup homeassistant docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ role_path }}/docker-compose.yml"


- name: Run docker-compose pull
  shell: "docker-compose pull --ignore-pull-failures || true"
  register: shell_output
  args:
    chdir: "{{ role_path }}"

- name: Deploy homeassistant Docker Compose stack
  docker_compose:
    recreate: "{{ 'always' if docker_recreate else 'smart' }}"
    project_src: "{{ role_path }}"
    remove_orphans: true
    files:
    - docker-compose.yml
  register: shell_output

#- name: Get Homeassistant docker IP
#  command: |
#         {% raw %}
#         docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' homeassistant
#         {% endraw %}
#  register: cmd_res
#  retries: 60
#  until: cmd_res.stdout is search('172')

#- name: Check container
#  wait_for:
#    host: "{{ cmd_res.stdout }}"
#    port: 8123

#- name: Install HACS
#  community.docker.docker_container_exec:
#    container: homeassistant
#    command: wget -O - https://get.hacs.xyz | bash -
#    detach: true
#    chdir : /tmp

#- pause: seconds=5

#- name: Restart homeassistant
#  docker_service:
#    project_src: "{{ role_path }}"
#    services:
#        - homeassistant
#    restarted: true
#    state: present


