- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"

- name: Home Assistant Docker Container
  docker_container:
    name: homeassistant
    log_options:
      max-size: 256m
      max-file: 1
    image: homeassistant/home-assistant
    pull: true
    volumes:
      - "{{ homeassistant_data_directory }}/config:/config:rw"
    network_mode: host
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    restart_policy: unless-stopped
    env:
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.enable: "{{ homeassistant_available_externally }}"
      traefik.http.routers.homeassistant.entrypoints: "web,websecure"
      traefik.http.routers.homeassistant.rule: "Host(`{{ homeassistant_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.homeassistant.tls.certresolver: "letsencrypt"
      traefik.http.routers.homeassistant.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.homeassistant.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
    memory: 1g
