---
prometheus_enabled: false
prometheus_available_externally: "false"

# directories
prometheus_data_directory: "{{ docker_home }}/prometheus"

# uid / gid
prometheus_user_id: "0"
prometheus_group_id: "0"

# network
prometheus_hostname: "prometheus"
prometheus_port: 9393

loki_available_externally: "false"
loki_hostname: "loki"
