---
- name: Create Syncthing Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ syncthing_data_directory }}"
- name: Syncthing Docker Container
  docker_container:
    name: syncthing
    image: syncthing/syncthing:latest
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    volumes: "{{ syncthing_volumes }}"
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    labels:
      traefik.enable: "{{ syncthing_available_externally }}"
      traefik.http.routers.syncthing.entrypoints: "websecure-ext,websecure"
      traefik.http.routers.syncthing.rule: "Host(`{{ syncthing_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.syncthing.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.syncthing.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"
