---
- name: OpenVPN
  docker_container:
    name: openvpn
    log_driver: json-file
    log_options:
      max-size: 256m
      max-file: "1"
    image: dperson/openvpn-client:latest
    networks:
      - name: "{{ nas_bridge_network }}"
    pull: true
    capabilities:
      - NET_ADMIN
    security_opts:
      - label:disable
    restart_policy: unless-stopped
    recreate: "{{ 'yes' if docker_recreate else 'no' }}"
    volumes:
      - "{{ openvpn_config_directory }}:/vpn"
      - "/dev/net/tun:/dev/net/tun:z"
 #   ports:
 #     - "9090:9090"
    memory: "{{ openvpn_memory }}"
    env:
      TZ: '{{ ansible_nas_timezone }}'
    tty: yes
    interactive: yes
    devices:
      - "/dev/net/tun:/dev/net/tun"
    tmpfs:
      - /run
      - /tmp
    dns_servers:
      - 1.1.1.1
