---
- name: set custom dns list
  template:
    src: custom.list.j2
    dest: "{{ pihole_data_directory }}/pihole/custom.list"
    owner: nasuser
    group: nasuser
    mode: '0660'

- name: restart pihole dns
  command: docker exec pihole bash -c 'pihole restartdns'
